import {
  LocationOption,
  ContextOption,
  PoseOption,
  CameraOption,
  LightingOption,
  PropOption,
  ClothingOption,
  HairstyleOption,
  ExpressionOption,
  EyewearOption,
  SaudiDetailOption,
} from './types';

// ==========================================
// 2017 RANGE ROVER SPORT AUTOBIOGRAPHY SPEC
// ==========================================
export const RANGE_ROVER_MY2017_SPEC = {
  model: '2017 Range Rover Sport Autobiography Dynamic (L494 pre-facelift)',
  specBadge: 'Saudi-spec GCC, Left-Hand Drive (LHD)',
  exterior:
    'Fuji White exterior finish, contrasting Santorini Gloss Black floating roof, black pillar trim, 21-inch diamond-turned split-spoke alloy wheels, red Brembo brake calipers, pre-facelift front bumper with distinctive lower air intakes and round LED daytime running light rings',
  interiorArchitecture:
    'MY2017 pre-facelift interior architecture featuring a single 10.2-inch InControl Touch Pro central display screen (not dual screens), three physical tactile rotary climate dials with digital temperature centers, aluminum rotary transmission gear selector, Terrain Response dial',
  upholstery:
    'Two-tone Ebony and Ivory semi-aniline perforated leather interior, Ivory perforated leather sports seats with winged headrests and subtle Autobiography embossing on the backrests',
  trimVeneer:
    'Grand Black / Extended Grand Black high-gloss piano lacquer veneer along the center console and door switch packs',
  roof:
    'Full fixed panoramic glass roof with the sunblind retracted, allowing natural ambient skylight to flood the luxury cabin',
  saudiTouches:
    'Saudi parking access card tucked neatly into the driver sun visor clip, clean dashboard, subtle ambient instrument backlighting',
};

// ==========================================
// EVERYDAY LOCATIONS
// ==========================================
export const BEDROOM_ZONES: LocationOption[] = [
  // --- VEHICLE & PARKING LOCATIONS ---
  {
    id: 'shaded_parking',
    name: 'Shaded Parking Area (Classic Fabric Shades)',
    category: 'vehicle_parking',
    description: 'Outdoor parking area covered by classic beige perforated fabric tensile shades, yellow-and-black curb stones, and smooth asphalt.',
    supportsVehicle: true,
    environmentDetails: [
      'Overhead perforated beige fabric parking shade canopy casting soft geometric shadows',
      'Curved steel support poles painted neutral gray or beige',
      'Asphalt parking surface with faded white stall lines and yellow-black painted concrete curbs',
      'Parked vehicles and clean everyday Saudi commercial or residential surroundings in the background',
    ],
    supportedContextIds: [
      'rr_driver_seat',
      'rr_passenger_seat',
      'rr_beside_driver_door',
      'rr_standing_front_hood',
      'rr_door_open_standing',
      'rr_background_casual',
      'outdoor_standing_shade',
    ],
    defaultContextId: 'rr_beside_driver_door',
    defaultLightingId: 'saudi_afternoon_warm',
    defaultPoseId: 'standing_car_door_lean',
    defaultCameraId: 'front_camera_eye_level',
    isStandingZone: true,
  },
  {
    id: 'open_parking',
    name: 'Open Commercial / Urban Parking Lot',
    category: 'vehicle_parking',
    description: 'Wide open outdoor commercial asphalt parking lot with distant everyday storefronts, light poles, and neighboring vehicles.',
    supportsVehicle: true,
    environmentDetails: [
      'Wide dark asphalt parking lot with painted stalls and concrete wheel-stops',
      'Tall modern steel parking light poles with LED fixture arrays',
      'Everyday storefront facades, palm tree planters, and quiet commercial background activity',
      'Warm ambient open sky with realistic natural heat haze in the distance',
    ],
    supportedContextIds: [
      'rr_driver_seat',
      'rr_beside_driver_door',
      'rr_standing_front_hood',
      'rr_background_casual',
      'outdoor_standing_shade',
    ],
    defaultContextId: 'rr_driver_seat',
    defaultLightingId: 'saudi_afternoon_warm',
    defaultPoseId: 'car_driver_handheld',
    defaultCameraId: 'car_interior_handheld',
    isStandingZone: false,
  },
  {
    id: 'gas_station',
    name: 'Roadside Gas Station & Service Stop',
    category: 'vehicle_parking',
    description: 'Well-lit modern Saudi service station fuel island, digital pump displays, clean tiled apron, and illuminated overhead canopy.',
    supportsVehicle: true,
    environmentDetails: [
      'Brightly lit fuel dispenser island with digital electronic fuel meters and clean pump nozzles',
      'High illuminated station canopy providing even diffuse overhead lighting',
      'Clean light-gray tiled drive area transitioning to asphalt apron',
      'Convenience store entrance with soft glass reflections and roadside highway lighting beyond',
    ],
    supportedContextIds: [
      'rr_beside_driver_door',
      'rr_driver_seat',
      'rr_standing_front_hood',
      'gas_station_curb_stand',
    ],
    defaultContextId: 'rr_beside_driver_door',
    defaultLightingId: 'gas_station_canopy_light',
    defaultPoseId: 'standing_car_door_lean',
    defaultCameraId: 'front_camera_eye_level',
    isStandingZone: true,
  },
  {
    id: 'desert_road_stop',
    name: 'Desert Roadside Shoulder / Highway Stop',
    category: 'vehicle_parking',
    description: 'Highway road shoulder where asphalt meets natural desert sand, open horizon, and gentle desert breeze.',
    supportsVehicle: true,
    environmentDetails: [
      'Black asphalt highway shoulder edge meeting fine light-golden desert sand and small gravel',
      'Vast open desert horizon with soft rolling dunes and low acacia shrubs far in the distance',
      'Clear Saudi desert sky with atmospheric warm dust haze near the horizon',
      'Solitary parked vehicle providing physical scale against the expansive desert landscape',
    ],
    supportedContextIds: [
      'rr_door_open_standing',
      'rr_standing_front_hood',
      'rr_beside_driver_door',
      'desert_roadside_stand',
    ],
    defaultContextId: 'rr_door_open_standing',
    defaultLightingId: 'saudi_afternoon_warm',
    defaultPoseId: 'door_open_step_pose',
    defaultCameraId: 'front_camera_eye_level',
    isStandingZone: true,
  },

  // --- STREETS & PUBLIC SPACES ---
  {
    id: 'residential_street',
    name: 'Quiet Residential Street (Villa Neighborhood)',
    category: 'streets_public',
    description: 'Peaceful residential neighborhood street with textured villa perimeter walls, modern sliding gates, paved sidewalks, and quiet suburban calmness.',
    supportsVehicle: true,
    environmentDetails: [
      'Textured beige profile-render (لياسة بروفايل) villa boundary wall with decorative black wrought-iron trim',
      'Interlocking concrete sidewalk pavers beside a clean asphalt neighborhood street',
      'Wall-mounted outdoor split AC compressor units and residential decorative wall lanterns',
      'Quiet afternoon neighborhood ambiance with subtle residential architecture and no crowds',
    ],
    supportedContextIds: [
      'street_sidewalk_walk',
      'street_villa_wall_lean',
      'rr_driver_seat',
      'rr_beside_driver_door',
    ],
    defaultContextId: 'street_sidewalk_walk',
    defaultLightingId: 'saudi_afternoon_warm',
    defaultPoseId: 'mid_stride_casual_walk',
    defaultCameraId: 'front_camera_eye_level',
    isStandingZone: true,
  },
  {
    id: 'commercial_walkway',
    name: 'Commercial Walkway & Sidewalk',
    category: 'streets_public',
    description: 'Paved urban pedestrian walkway in front of modern boutique retail stores, minimalist glass shopfronts, and landscaped sidewalk planters.',
    supportsVehicle: false,
    environmentDetails: [
      'Large square granite or basalt sidewalk pavers with clean expansion joints',
      'Modern frameless glass shopfront windows with soft ambient indoor display glow',
      'Neat architectural concrete planters with ornamental grasses and dwarf date palms',
      'Pedestrian walkway perspective with realistic everyday urban depth',
    ],
    supportedContextIds: [
      'walkway_mid_stride',
      'walkway_storefront_lean',
    ],
    defaultContextId: 'walkway_mid_stride',
    defaultLightingId: 'saudi_afternoon_warm',
    defaultPoseId: 'mid_stride_casual_walk',
    defaultCameraId: 'front_camera_eye_level',
    isStandingZone: true,
  },
  {
    id: 'outdoor_cafe',
    name: 'Outdoor Sidewalk Café',
    category: 'streets_public',
    description: 'Relaxed outdoor seating area of an urban specialty coffee shop, small black steel tables, modern chairs, and paved walkway ambiance.',
    supportsVehicle: false,
    environmentDetails: [
      'Dark anthracite stone patio tiles with neat café boundary glass screens',
      'Compact matte black bistro table holding an iced beverage or takeaway coffee cup',
      'Warm ambient lighting from café exterior fixtures and bistro string lights',
      'Casual urban lifestyle setting with relaxed pedestrian passersby softly blurred in the background',
    ],
    supportedContextIds: [
      'seated_outdoor_table',
      'cafe_entrance_waiting',
    ],
    defaultContextId: 'seated_outdoor_table',
    defaultLightingId: 'cafe_string_lights',
    defaultPoseId: 'seated_cafe_table_pose',
    defaultCameraId: 'front_camera_chest_tilt',
    isStandingZone: false,
  },
  {
    id: 'neighborhood_park',
    name: 'Neighborhood Walkway & Garden Park',
    category: 'streets_public',
    description: 'Green neighborhood public walking park with paved running tracks, date palms, landscaped hedges, and modern park benches.',
    supportsVehicle: false,
    environmentDetails: [
      'Terra-cotta tinted rubberized walking track alongside dark interlocking stone pavers',
      'Mature date palms and manicured desert-adapted shrubs along the walkway',
      'Modern slatted wooden and iron park bench under soft ambient tree canopy',
      'Peaceful afternoon recreational environment with soft golden hour light filtering through palm fronds',
    ],
    supportedContextIds: [
      'bench_park_sit',
      'walkway_mid_stride',
    ],
    defaultContextId: 'bench_park_sit',
    defaultLightingId: 'saudi_afternoon_warm',
    defaultPoseId: 'bench_park_relax',
    defaultCameraId: 'front_camera_eye_level',
    isStandingZone: false,
  },
  {
    id: 'building_entrance',
    name: 'Modern Building Glass Entrance',
    category: 'streets_public',
    description: 'Sleek contemporary building foyer entrance with frameless glass doors, polished stone facade, and architectural downlighting.',
    supportsVehicle: false,
    environmentDetails: [
      'Tall architectural glass revolving door and frameless glass panels reflecting city evening tones',
      'Honed gray limestone or travertine entrance pillars with subtle recessed LED channel lights',
      'Polished entrance landing with stainless steel door handles and clean minimalist lines',
      'Spontaneous everyday snapshot capturing an urban transition moment',
    ],
    supportedContextIds: [
      'building_entry_wait',
      'walkway_mid_stride',
    ],
    defaultContextId: 'building_entry_wait',
    defaultLightingId: 'saudi_night_streetlights',
    defaultPoseId: 'wall_lean_relaxed',
    defaultCameraId: 'front_camera_eye_level',
    isStandingZone: true,
  },

  // --- INDOOR & ARCHITECTURAL ---
  {
    id: 'elevator_mirror',
    name: 'Modern Elevator (Mirror Selfie)',
    category: 'indoor_living',
    description: 'Inside a sleek modern residential or commercial elevator with brushed stainless steel walls and a crystal-clear full-width mirror.',
    supportsVehicle: false,
    environmentDetails: [
      'Flawless full-width elevator back mirror reflecting the interior cabin and subject',
      'Brushed stainless steel side walls, handrail, and illuminated floor indicator buttons',
      'Soft diffused recessed LED ceiling panel casting even, flattering overhead lighting',
      'Smartphone clearly held in hand with its screen and camera module visible in mirror reflection',
    ],
    supportedContextIds: ['elevator_mirror_ctx'],
    defaultContextId: 'elevator_mirror_ctx',
    defaultLightingId: 'overhead_room_light',
    defaultPoseId: 'standing_mirror_full_length',
    defaultCameraId: 'mirror_selfie_handheld',
    isStandingZone: true,
  },
  {
    id: 'building_rooftop',
    name: 'Building Rooftop (Residential Skyline)',
    category: 'indoor_living',
    description: 'Open residential building flat roof with parapet wall, water tank structures, satellite dishes, and a vast open suburban sky.',
    supportsVehicle: false,
    environmentDetails: [
      'Beige water-resistant tiled rooftop floor with low masonry perimeter parapet wall',
      'Distant low-rise residential neighborhood skyline with villa rooftops, minarets, and warm twilight sky',
      'Subtle residential rooftop fixtures including outdoor split AC compressors and neatly routed conduit',
      'Open air atmosphere with gentle late-day breeze and warm sunset glow on walls',
    ],
    supportedContextIds: ['rooftop_ledge_stand'],
    defaultContextId: 'rooftop_ledge_stand',
    defaultLightingId: 'saudi_afternoon_warm',
    defaultPoseId: 'wall_lean_relaxed',
    defaultCameraId: 'front_camera_eye_level',
    isStandingZone: true,
  },
  {
    id: 'on_the_bed',
    name: 'On the Bed (Bedroom Relaxation)',
    category: 'indoor_living',
    description: 'Relaxed on a comfortable bed with soft textured duvet, plush pillows, and an upholstered or wooden headboard.',
    supportsVehicle: false,
    environmentDetails: [
      'Soft rumpled white cotton or linen duvet and textured throw blanket',
      'Plush sleeping pillows stacked against the headboard',
      'Warm bedside nightstand with small lamp and charging cable nearby',
      'Cozy, authentic private bedroom atmosphere with ambient room depth in background',
    ],
    supportedContextIds: ['propped_against_headboard', 'resting_on_elbow_bed', 'lying_back_on_bed', 'sitting_on_bed_edge'],
    defaultContextId: 'resting_on_elbow_bed',
    defaultLightingId: 'warm_nightstand_lamp',
    defaultPoseId: 'resting_on_elbow_bed',
    defaultCameraId: 'front_camera_eye_level',
    isStandingZone: false,
  },
  {
    id: 'bedroom_mirror',
    name: 'In Front of the Bedroom Mirror',
    category: 'indoor_living',
    description: 'Standing in front of a full-length wardrobe mirror or vanity dresser mirror, capturing a casual everyday mirror selfie.',
    supportsVehicle: false,
    environmentDetails: [
      'Clean full-length bedroom mirror or vanity mirror reflecting the room interior',
      'Background in reflection shows the cozy unmade bed, bedroom rug, and wooden furniture',
      'Smartphone clearly visible in hand, showing the reflection',
      'Authentic bedroom mirror reflection with true room perspective',
    ],
    supportedContextIds: ['standing_mirror_full_length_ctx'],
    defaultContextId: 'standing_mirror_full_length_ctx',
    defaultLightingId: 'overhead_room_light',
    defaultPoseId: 'standing_mirror_full_length',
    defaultCameraId: 'mirror_selfie_handheld',
    isStandingZone: true,
  },
  {
    id: 'bedroom_window',
    name: 'By the Bedroom Window',
    category: 'indoor_living',
    description: 'Beside the bedroom window with sheer curtains filtering ambient outdoor light.',
    supportsVehicle: false,
    environmentDetails: [
      'Floor-to-ceiling or large bedroom window with translucent sheer white curtains',
      'Ambient natural light filtered through curtain fabric creating soft wrap',
      'Bedroom floor and interior room depth visible softly in background',
      'Quiet indoor bedroom atmosphere with calm window illumination',
    ],
    supportedContextIds: ['standing_by_curtain'],
    defaultContextId: 'standing_by_curtain',
    defaultLightingId: 'natural_window_daylight',
    defaultPoseId: 'standing_next_to_window',
    defaultCameraId: 'front_camera_eye_level',
    isStandingZone: true,
  },
  {
    id: 'bedroom_middle',
    name: 'In the Middle of the Bedroom',
    category: 'indoor_living',
    description: 'Standing freely in the open central space of the bedroom, bed and room decor visible in the soft background.',
    supportsVehicle: false,
    environmentDetails: [
      'Open carpeted or wooden bedroom floor area',
      'Unmade bed with pillows softly out of focus in the background',
      'Warm residential bedroom wall color and cozy interior atmosphere',
      'Natural arm-length wide-angle selfie perspective capturing subject and room',
    ],
    supportedContextIds: ['standing_middle_bedroom_ctx'],
    defaultContextId: 'standing_middle_bedroom_ctx',
    defaultLightingId: 'overhead_room_light',
    defaultPoseId: 'standing_middle_of_bedroom',
    defaultCameraId: 'front_camera_eye_level',
    isStandingZone: true,
  },
  {
    id: 'bedroom_wardrobe',
    name: 'Beside the Bedroom Wardrobe/Closet',
    category: 'indoor_living',
    description: 'Standing beside the wooden wardrobe or built-in closet doors.',
    supportsVehicle: false,
    environmentDetails: [
      'Tall bedroom wardrobe or built-in closet with clean wood-grain paneling',
      'Nightstand table and interior room wall visible to one side',
      'Casual indoor lifestyle room setting',
      'Soft diffused indoor light falling across clothing and wardrobe surface',
    ],
    supportedContextIds: ['standing_wardrobe_ctx'],
    defaultContextId: 'standing_wardrobe_ctx',
    defaultLightingId: 'overhead_room_light',
    defaultPoseId: 'standing_beside_wardrobe',
    defaultCameraId: 'front_camera_eye_level',
    isStandingZone: true,
  },
  {
    id: 'bedroom_door',
    name: 'Near the Bedroom Door',
    category: 'indoor_living',
    description: 'Standing near the closed bedroom door, showing interior bedroom wall and door trim.',
    supportsVehicle: false,
    environmentDetails: [
      'Clean closed interior bedroom door with brushed handle',
      'Neutral painted bedroom drywall and light switch',
      'Bed and nightstand softly receding in the background',
      'Spontaneous snapshot taken before heading out or after entering the room',
    ],
    supportedContextIds: ['standing_door_ctx'],
    defaultContextId: 'standing_door_ctx',
    defaultLightingId: 'overhead_room_light',
    defaultPoseId: 'standing_near_bedroom_door',
    defaultCameraId: 'front_camera_eye_level',
    isStandingZone: true,
  },
  {
    id: 'bedroom_chair',
    name: 'Relaxing on a Bedroom Chair',
    category: 'indoor_living',
    description: 'Sitting back in a comfortable upholstered accent armchair or desk chair in the corner of the bedroom.',
    supportsVehicle: false,
    environmentDetails: [
      'Deep cushioned accent armchair or contemporary desk chair',
      'Bed and warm bedside table softly out of focus in the background',
      'Textured throw pillow resting behind the lower back',
      'Cozy private room setting with quiet indoor ambiance',
    ],
    supportedContextIds: ['lounging_accent_armchair'],
    defaultContextId: 'lounging_accent_armchair',
    defaultLightingId: 'warm_nightstand_lamp',
    defaultPoseId: 'chair_lounging_selfie',
    defaultCameraId: 'front_camera_eye_level',
    isStandingZone: false,
  },
];

// ==========================================
// SCENE CONTEXTS
// ==========================================
export const BEDROOM_CONTEXTS: ContextOption[] = [
  // --- RANGE ROVER VEHICLE CONTEXTS ---
  {
    id: 'rr_driver_seat',
    name: 'Inside 2017 Range Rover Sport (Driver Seat)',
    description: 'Sitting in the driver seat of the 2017 Range Rover Sport Autobiography Dynamic (L494 pre-facelift), Left-Hand Drive (LHD). Ivory perforated leather sports seat, Ebony upper dash, single 10.2-inch InControl Touch Pro display, physical rotary climate dials, and Grand Black lacquer veneer visible.',
    isVehicleContext: true,
    vehicleRole: 'inside_driver',
    isMirrorContext: false,
    isStandingContext: false,
    allowedZoneIds: ['shaded_parking', 'open_parking', 'gas_station', 'residential_street'],
    defaultPoseId: 'car_driver_handheld',
    defaultCameraId: 'car_interior_handheld',
    allowedPoseIds: ['car_driver_handheld', 'car_steering_wheel_rest'],
    allowedCameraIds: ['car_interior_handheld', 'front_camera_eye_level'],
    allowedLightingIds: ['saudi_afternoon_warm', 'car_interior_ambient', 'saudi_midday_harsh', 'saudi_night_streetlights'],
    allowedPropIds: ['prop_none', 'prop_car_keys', 'prop_sunglasses', 'prop_paper_cup'],
  },
  {
    id: 'rr_passenger_seat',
    name: 'Inside 2017 Range Rover Sport (Passenger Seat)',
    description: 'Relaxed in the front passenger seat of the 2017 Range Rover Sport Autobiography Dynamic. Ivory perforated leather, Grand Black door veneer, panoramic glass roof overhead with open sunblind.',
    isVehicleContext: true,
    vehicleRole: 'inside_passenger',
    isMirrorContext: false,
    isStandingContext: false,
    allowedZoneIds: ['shaded_parking', 'open_parking'],
    defaultPoseId: 'car_passenger_chill',
    defaultCameraId: 'car_interior_handheld',
    allowedPoseIds: ['car_passenger_chill'],
    allowedCameraIds: ['car_interior_handheld', 'front_camera_eye_level'],
    allowedLightingIds: ['saudi_afternoon_warm', 'car_interior_ambient', 'saudi_midday_harsh'],
    allowedPropIds: ['prop_none', 'prop_cold_drink', 'prop_airpods_case'],
  },
  {
    id: 'rr_beside_driver_door',
    name: 'Beside Range Rover Driver Door',
    description: 'Standing beside the Fuji White 2017 Range Rover Sport near the driver door, showing the pre-facelift body lines, gloss black floating roof, red Brembo calipers, and 21-inch diamond-turned alloys.',
    isVehicleContext: true,
    vehicleRole: 'beside_driver_door',
    isMirrorContext: false,
    isStandingContext: true,
    allowedZoneIds: ['shaded_parking', 'open_parking', 'gas_station', 'residential_street', 'desert_road_stop'],
    defaultPoseId: 'standing_car_door_lean',
    defaultCameraId: 'front_camera_eye_level',
    allowedPoseIds: ['standing_car_door_lean', 'door_open_step_pose'],
    allowedCameraIds: ['front_camera_eye_level', 'front_camera_chest_tilt'],
    allowedLightingIds: ['saudi_afternoon_warm', 'saudi_midday_harsh', 'gas_station_canopy_light', 'saudi_night_streetlights'],
    allowedPropIds: ['prop_none', 'prop_car_keys', 'prop_sunglasses', 'prop_paper_cup'],
  },
  {
    id: 'rr_standing_front_hood',
    name: 'Near Front Fender / Hood of Range Rover',
    description: 'Standing casually near the front fender of the Fuji White 2017 Range Rover Sport, pre-facelift clamshell hood and signature LED daytime running light rings visible behind.',
    isVehicleContext: true,
    vehicleRole: 'front_hood_lean',
    isMirrorContext: false,
    isStandingContext: true,
    allowedZoneIds: ['shaded_parking', 'open_parking', 'gas_station', 'desert_road_stop'],
    defaultPoseId: 'standing_hood_casual',
    defaultCameraId: 'front_camera_eye_level',
    allowedPoseIds: ['standing_hood_casual', 'mid_stride_casual_walk'],
    allowedCameraIds: ['front_camera_eye_level', 'front_camera_chest_tilt'],
    allowedLightingIds: ['saudi_afternoon_warm', 'saudi_midday_harsh', 'gas_station_canopy_light', 'saudi_night_streetlights'],
    allowedPropIds: ['prop_none', 'prop_sunglasses', 'prop_car_keys'],
  },
  {
    id: 'rr_door_open_standing',
    name: 'Range Rover Open Door Step',
    description: 'Standing with the driver door open, one foot on the door sill and one on the ground, creating a dynamic spontaneous automotive moment.',
    isVehicleContext: true,
    vehicleRole: 'door_open_standing',
    isMirrorContext: false,
    isStandingContext: true,
    allowedZoneIds: ['shaded_parking', 'desert_road_stop'],
    defaultPoseId: 'door_open_step_pose',
    defaultCameraId: 'front_camera_eye_level',
    allowedPoseIds: ['door_open_step_pose', 'standing_car_door_lean'],
    allowedCameraIds: ['front_camera_eye_level'],
    allowedLightingIds: ['saudi_afternoon_warm', 'saudi_midday_harsh'],
    allowedPropIds: ['prop_none', 'prop_car_keys', 'prop_sunglasses'],
  },
  {
    id: 'rr_background_casual',
    name: 'Casual Parking Selfie (Vehicle in Background)',
    description: 'Walking or standing in the parking lot with the Fuji White 2017 Range Rover Sport parked naturally in the background among other vehicles.',
    isVehicleContext: true,
    vehicleRole: 'vehicle_in_background',
    isMirrorContext: false,
    isStandingContext: true,
    allowedZoneIds: ['shaded_parking', 'open_parking'],
    defaultPoseId: 'mid_stride_casual_walk',
    defaultCameraId: 'front_camera_eye_level',
    allowedPoseIds: ['mid_stride_casual_walk', 'standing_curb_relax'],
    allowedCameraIds: ['front_camera_eye_level', 'front_camera_chest_tilt'],
    allowedLightingIds: ['saudi_afternoon_warm', 'saudi_midday_harsh', 'saudi_night_streetlights'],
    allowedPropIds: ['prop_none', 'prop_paper_cup', 'prop_sunglasses'],
  },

  // --- OUTDOOR NON-VEHICLE CONTEXTS ---
  {
    id: 'outdoor_standing_shade',
    name: 'Standing Under Parking Fabric Shade',
    description: 'Standing relaxed under the tensile parking fabric shade canopy, filtered sunlight, clean asphalt and yellow-black curbs around.',
    isVehicleContext: false,
    vehicleRole: 'none',
    isMirrorContext: false,
    isStandingContext: true,
    allowedZoneIds: ['shaded_parking', 'open_parking'],
    defaultPoseId: 'standing_curb_relax',
    defaultCameraId: 'front_camera_eye_level',
    allowedPoseIds: ['standing_curb_relax', 'mid_stride_casual_walk'],
    allowedCameraIds: ['front_camera_eye_level', 'front_camera_chest_tilt'],
    allowedLightingIds: ['saudi_afternoon_warm', 'saudi_midday_harsh', 'saudi_night_streetlights'],
    allowedPropIds: ['prop_none', 'prop_paper_cup', 'prop_sunglasses'],
  },
  {
    id: 'gas_station_curb_stand',
    name: 'Standing near Gas Station Convenience Store',
    description: 'Taking a quick spontaneous selfie outside the service station convenience store with illuminated fuel canopy in the background.',
    isVehicleContext: false,
    vehicleRole: 'none',
    isMirrorContext: false,
    isStandingContext: true,
    allowedZoneIds: ['gas_station'],
    defaultPoseId: 'standing_curb_relax',
    defaultCameraId: 'front_camera_eye_level',
    allowedPoseIds: ['standing_curb_relax', 'mid_stride_casual_walk'],
    allowedCameraIds: ['front_camera_eye_level'],
    allowedLightingIds: ['gas_station_canopy_light', 'saudi_night_streetlights'],
    allowedPropIds: ['prop_none', 'prop_paper_cup', 'prop_cold_drink'],
  },
  {
    id: 'desert_roadside_stand',
    name: 'Standing on Desert Highway Shoulder',
    description: 'Standing on the edge of the desert highway, vast open desert sand, warm wind, and expansive sky.',
    isVehicleContext: false,
    vehicleRole: 'none',
    isMirrorContext: false,
    isStandingContext: true,
    allowedZoneIds: ['desert_road_stop'],
    defaultPoseId: 'standing_curb_relax',
    defaultCameraId: 'front_camera_eye_level',
    allowedPoseIds: ['standing_curb_relax', 'mid_stride_casual_walk'],
    allowedCameraIds: ['front_camera_eye_level', 'front_camera_chest_tilt'],
    allowedLightingIds: ['saudi_afternoon_warm', 'saudi_midday_harsh'],
    allowedPropIds: ['prop_none', 'prop_sunglasses'],
  },
  {
    id: 'street_sidewalk_walk',
    name: 'Walking Along Residential Sidewalk',
    description: 'Casual mid-stride walk along the paved sidewalk of a quiet villa neighborhood, warm afternoon sunlight, clean quiet street.',
    isVehicleContext: false,
    vehicleRole: 'none',
    isMirrorContext: false,
    isStandingContext: true,
    allowedZoneIds: ['residential_street'],
    defaultPoseId: 'mid_stride_casual_walk',
    defaultCameraId: 'front_camera_eye_level',
    allowedPoseIds: ['mid_stride_casual_walk', 'standing_curb_relax'],
    allowedCameraIds: ['front_camera_eye_level', 'front_camera_chest_tilt'],
    allowedLightingIds: ['saudi_afternoon_warm', 'saudi_night_streetlights'],
    allowedPropIds: ['prop_none', 'prop_airpods_case', 'prop_paper_cup'],
  },
  {
    id: 'street_villa_wall_lean',
    name: 'Leaning near Residential Villa Wall',
    description: 'Standing relaxed near a textured beige villa boundary wall and ornamental iron gate, quiet neighborhood setting.',
    isVehicleContext: false,
    vehicleRole: 'none',
    isMirrorContext: false,
    isStandingContext: true,
    allowedZoneIds: ['residential_street'],
    defaultPoseId: 'wall_lean_relaxed',
    defaultCameraId: 'front_camera_eye_level',
    allowedPoseIds: ['wall_lean_relaxed', 'standing_curb_relax'],
    allowedCameraIds: ['front_camera_eye_level', 'front_camera_chest_tilt'],
    allowedLightingIds: ['saudi_afternoon_warm', 'saudi_night_streetlights'],
    allowedPropIds: ['prop_none', 'prop_paper_cup'],
  },
  {
    id: 'walkway_mid_stride',
    name: 'Mid-Stride Walk on Commercial Pavement',
    description: 'Dynamic casual walk along a wide paved commercial sidewalk, modern boutique storefronts, and clean granite pavers.',
    isVehicleContext: false,
    vehicleRole: 'none',
    isMirrorContext: false,
    isStandingContext: true,
    allowedZoneIds: ['commercial_walkway', 'neighborhood_park', 'building_entrance'],
    defaultPoseId: 'mid_stride_casual_walk',
    defaultCameraId: 'front_camera_eye_level',
    allowedPoseIds: ['mid_stride_casual_walk', 'standing_curb_relax'],
    allowedCameraIds: ['front_camera_eye_level', 'front_camera_chest_tilt'],
    allowedLightingIds: ['saudi_afternoon_warm', 'saudi_night_streetlights'],
    allowedPropIds: ['prop_none', 'prop_paper_cup', 'prop_cold_drink', 'prop_airpods_case'],
  },
  {
    id: 'walkway_storefront_lean',
    name: 'Standing near Boutique Storefront',
    description: 'Relaxed stance near a modern minimalist retail storefront glass window with soft warm interior illumination.',
    isVehicleContext: false,
    vehicleRole: 'none',
    isMirrorContext: false,
    isStandingContext: true,
    allowedZoneIds: ['commercial_walkway'],
    defaultPoseId: 'wall_lean_relaxed',
    defaultCameraId: 'front_camera_eye_level',
    allowedPoseIds: ['wall_lean_relaxed', 'standing_curb_relax'],
    allowedCameraIds: ['front_camera_eye_level'],
    allowedLightingIds: ['saudi_afternoon_warm', 'saudi_night_streetlights'],
    allowedPropIds: ['prop_none', 'prop_paper_cup'],
  },
  {
    id: 'seated_outdoor_table',
    name: 'Seated at Sidewalk Café Table',
    description: 'Sitting at an outdoor café table, arm resting casually on the tabletop next to an iced beverage, relaxed urban lifestyle vibe.',
    isVehicleContext: false,
    vehicleRole: 'none',
    isMirrorContext: false,
    isStandingContext: false,
    allowedZoneIds: ['outdoor_cafe'],
    defaultPoseId: 'seated_cafe_table_pose',
    defaultCameraId: 'front_camera_chest_tilt',
    allowedPoseIds: ['seated_cafe_table_pose'],
    allowedCameraIds: ['front_camera_chest_tilt', 'front_camera_eye_level'],
    allowedLightingIds: ['cafe_string_lights', 'saudi_afternoon_warm', 'saudi_night_streetlights'],
    allowedPropIds: ['prop_none', 'prop_cold_drink', 'prop_paper_cup', 'prop_sunglasses'],
  },
  {
    id: 'cafe_entrance_waiting',
    name: 'Waiting Outside Coffee Shop',
    description: 'Standing outside coffee shop entrance holding takeaway cup, casual everyday urban moment.',
    isVehicleContext: false,
    vehicleRole: 'none',
    isMirrorContext: false,
    isStandingContext: true,
    allowedZoneIds: ['outdoor_cafe'],
    defaultPoseId: 'standing_curb_relax',
    defaultCameraId: 'front_camera_eye_level',
    allowedPoseIds: ['standing_curb_relax', 'mid_stride_casual_walk'],
    allowedCameraIds: ['front_camera_eye_level'],
    allowedLightingIds: ['cafe_string_lights', 'saudi_afternoon_warm', 'saudi_night_streetlights'],
    allowedPropIds: ['prop_none', 'prop_paper_cup'],
  },
  {
    id: 'bench_park_sit',
    name: 'Sitting on Park Bench',
    description: 'Resting casually on a park bench surrounded by date palms, paved walking tracks, and soft afternoon light.',
    isVehicleContext: false,
    vehicleRole: 'none',
    isMirrorContext: false,
    isStandingContext: false,
    allowedZoneIds: ['neighborhood_park'],
    defaultPoseId: 'bench_park_relax',
    defaultCameraId: 'front_camera_eye_level',
    allowedPoseIds: ['bench_park_relax'],
    allowedCameraIds: ['front_camera_eye_level', 'front_camera_high_angle'],
    allowedLightingIds: ['saudi_afternoon_warm'],
    allowedPropIds: ['prop_none', 'prop_airpods_case', 'prop_cold_drink'],
  },
  {
    id: 'building_entry_wait',
    name: 'Waiting by Modern Building Entrance',
    description: 'Standing beside polished stone entrance columns and glass architectural facade, subtle reflections of the street.',
    isVehicleContext: false,
    vehicleRole: 'none',
    isMirrorContext: false,
    isStandingContext: true,
    allowedZoneIds: ['building_entrance'],
    defaultPoseId: 'wall_lean_relaxed',
    defaultCameraId: 'front_camera_eye_level',
    allowedPoseIds: ['wall_lean_relaxed', 'standing_curb_relax'],
    allowedCameraIds: ['front_camera_eye_level'],
    allowedLightingIds: ['saudi_night_streetlights', 'saudi_afternoon_warm'],
    allowedPropIds: ['prop_none', 'prop_paper_cup'],
  },
  {
    id: 'rooftop_ledge_stand',
    name: 'Standing on Building Rooftop',
    description: 'Standing near the rooftop parapet wall overlooking quiet suburban residential rooftops and open twilight sky.',
    isVehicleContext: false,
    vehicleRole: 'none',
    isMirrorContext: false,
    isStandingContext: true,
    allowedZoneIds: ['building_rooftop'],
    defaultPoseId: 'wall_lean_relaxed',
    defaultCameraId: 'front_camera_eye_level',
    allowedPoseIds: ['wall_lean_relaxed', 'mid_stride_casual_walk'],
    allowedCameraIds: ['front_camera_eye_level', 'front_camera_high_angle'],
    allowedLightingIds: ['saudi_afternoon_warm', 'saudi_night_streetlights'],
    allowedPropIds: ['prop_none', 'prop_airpods_case'],
  },

  // --- INDOOR & BEDROOM CONTEXTS ---
  {
    id: 'elevator_mirror_ctx',
    name: 'Inside Elevator (Mirror Reflection)',
    description: 'Standing in modern building elevator holding smartphone at chest level, capturing clear reflection in full-width back mirror.',
    isVehicleContext: false,
    vehicleRole: 'none',
    isMirrorContext: true,
    isStandingContext: true,
    allowedZoneIds: ['elevator_mirror'],
    defaultPoseId: 'standing_mirror_full_length',
    defaultCameraId: 'mirror_selfie_handheld',
    allowedPoseIds: ['standing_mirror_full_length'],
    allowedCameraIds: ['mirror_selfie_handheld'],
    allowedLightingIds: ['overhead_room_light'],
    allowedPropIds: ['prop_none', 'prop_paper_cup', 'prop_airpods_case'],
  },
  {
    id: 'resting_on_elbow_bed',
    name: 'Resting on One Elbow on Bed',
    description: 'Propped casually on one elbow on the bed mattress, torso elevated at 35 degrees, single active arm holding phone forward.',
    isVehicleContext: false,
    vehicleRole: 'none',
    isMirrorContext: false,
    isStandingContext: false,
    allowedZoneIds: ['on_the_bed'],
    defaultPoseId: 'resting_on_elbow_bed',
    defaultCameraId: 'front_camera_eye_level',
    allowedPoseIds: ['resting_on_elbow_bed', 'propped_bed_one_handed', 'lying_overhead_selfie'],
    allowedCameraIds: ['front_camera_eye_level', 'front_camera_high_angle'],
    allowedLightingIds: ['warm_nightstand_lamp', 'pitch_dark_screen_glow', 'bright_morning_daylight'],
    allowedPropIds: ['prop_none', 'prop_airpods_case'],
  },
  {
    id: 'propped_against_headboard',
    name: 'Propped Against Headboard Pillows',
    description: 'Sitting up comfortably in bed with back supported by stacked pillows against the headboard.',
    isVehicleContext: false,
    vehicleRole: 'none',
    isMirrorContext: false,
    isStandingContext: false,
    allowedZoneIds: ['on_the_bed'],
    defaultPoseId: 'propped_bed_one_handed',
    defaultCameraId: 'front_camera_eye_level',
    allowedPoseIds: ['propped_bed_one_handed', 'resting_on_elbow_bed'],
    allowedCameraIds: ['front_camera_eye_level', 'front_camera_high_angle'],
    allowedLightingIds: ['warm_nightstand_lamp', 'bright_morning_daylight', 'pitch_dark_screen_glow'],
    allowedPropIds: ['prop_none', 'prop_airpods_case'],
  },
  {
    id: 'lying_back_on_bed',
    name: 'Lying Back Casually on the Mattress',
    description: 'Resting flat or slightly elevated on the bed, holding smartphone overhead at arm distance.',
    isVehicleContext: false,
    vehicleRole: 'none',
    isMirrorContext: false,
    isStandingContext: false,
    allowedZoneIds: ['on_the_bed'],
    defaultPoseId: 'lying_overhead_selfie',
    defaultCameraId: 'front_camera_high_angle',
    allowedPoseIds: ['lying_overhead_selfie', 'resting_on_elbow_bed'],
    allowedCameraIds: ['front_camera_high_angle'],
    allowedLightingIds: ['warm_nightstand_lamp', 'pitch_dark_screen_glow'],
    allowedPropIds: ['prop_none'],
  },
  {
    id: 'sitting_on_bed_edge',
    name: 'Seated on Bed Edge',
    description: 'Sitting on the edge of the mattress, feet planted on the floor, holding smartphone at eye level.',
    isVehicleContext: false,
    vehicleRole: 'none',
    isMirrorContext: false,
    isStandingContext: false,
    allowedZoneIds: ['on_the_bed'],
    defaultPoseId: 'bed_edge_forward_lean',
    defaultCameraId: 'front_camera_eye_level',
    allowedPoseIds: ['bed_edge_forward_lean'],
    allowedCameraIds: ['front_camera_eye_level'],
    allowedLightingIds: ['warm_nightstand_lamp', 'bright_morning_daylight'],
    allowedPropIds: ['prop_none'],
  },
  {
    id: 'standing_by_curtain',
    name: 'Standing by Sheer Window Curtains',
    description: 'Standing beside translucent sheer curtains, soft daylight wrapping the subject.',
    isVehicleContext: false,
    vehicleRole: 'none',
    isMirrorContext: false,
    isStandingContext: true,
    allowedZoneIds: ['bedroom_window'],
    defaultPoseId: 'standing_next_to_window',
    defaultCameraId: 'front_camera_eye_level',
    allowedPoseIds: ['standing_next_to_window'],
    allowedCameraIds: ['front_camera_eye_level'],
    allowedLightingIds: ['natural_window_daylight', 'bright_morning_daylight'],
    allowedPropIds: ['prop_none'],
  },
  {
    id: 'standing_mirror_full_length_ctx',
    name: 'Standing Mirror Reflection (Full-Length)',
    description: 'Standing in front of a full-length wardrobe mirror, capturing full posture with device in hand.',
    isVehicleContext: false,
    vehicleRole: 'none',
    isMirrorContext: true,
    isStandingContext: true,
    allowedZoneIds: ['bedroom_mirror'],
    defaultPoseId: 'standing_mirror_full_length',
    defaultCameraId: 'mirror_selfie_handheld',
    allowedPoseIds: ['standing_mirror_full_length'],
    allowedCameraIds: ['mirror_selfie_handheld'],
    allowedLightingIds: ['overhead_room_light', 'warm_nightstand_lamp'],
    allowedPropIds: ['prop_none'],
  },
  {
    id: 'standing_middle_bedroom_ctx',
    name: 'Standing in Bedroom Open Center',
    description: 'Standing freely in the middle of the room, bed and decor visible in soft background.',
    isVehicleContext: false,
    vehicleRole: 'none',
    isMirrorContext: false,
    isStandingContext: true,
    allowedZoneIds: ['bedroom_middle'],
    defaultPoseId: 'standing_middle_of_bedroom',
    defaultCameraId: 'front_camera_eye_level',
    allowedPoseIds: ['standing_middle_of_bedroom'],
    allowedCameraIds: ['front_camera_eye_level'],
    allowedLightingIds: ['overhead_room_light', 'warm_nightstand_lamp'],
    allowedPropIds: ['prop_none'],
  },
  {
    id: 'standing_wardrobe_ctx',
    name: 'Standing Beside Wardrobe Doors',
    description: 'Standing beside wooden wardrobe paneling, casual home environment.',
    isVehicleContext: false,
    vehicleRole: 'none',
    isMirrorContext: false,
    isStandingContext: true,
    allowedZoneIds: ['bedroom_wardrobe'],
    defaultPoseId: 'standing_beside_wardrobe',
    defaultCameraId: 'front_camera_eye_level',
    allowedPoseIds: ['standing_beside_wardrobe'],
    allowedCameraIds: ['front_camera_eye_level'],
    allowedLightingIds: ['overhead_room_light', 'warm_nightstand_lamp'],
    allowedPropIds: ['prop_none'],
  },
  {
    id: 'standing_door_ctx',
    name: 'Standing Near Closed Bedroom Door',
    description: 'Standing near interior door, spontaneous snapshot before leaving.',
    isVehicleContext: false,
    vehicleRole: 'none',
    isMirrorContext: false,
    isStandingContext: true,
    allowedZoneIds: ['bedroom_door'],
    defaultPoseId: 'standing_near_bedroom_door',
    defaultCameraId: 'front_camera_eye_level',
    allowedPoseIds: ['standing_near_bedroom_door'],
    allowedCameraIds: ['front_camera_eye_level'],
    allowedLightingIds: ['overhead_room_light'],
    allowedPropIds: ['prop_none'],
  },
  {
    id: 'lounging_accent_armchair',
    name: 'Lounging Back in Armchair',
    description: 'Seated back comfortably in an accent chair in the room corner.',
    isVehicleContext: false,
    vehicleRole: 'none',
    isMirrorContext: false,
    isStandingContext: false,
    allowedZoneIds: ['bedroom_chair'],
    defaultPoseId: 'chair_lounging_selfie',
    defaultCameraId: 'front_camera_eye_level',
    allowedPoseIds: ['chair_lounging_selfie'],
    allowedCameraIds: ['front_camera_eye_level'],
    allowedLightingIds: ['warm_nightstand_lamp'],
    allowedPropIds: ['prop_none'],
  },
];

// ==========================================
// POSES & BIOMECHANICS
// ==========================================
export const BEDROOM_POSES: PoseOption[] = [
  // --- VEHICLE POSES ---
  {
    id: 'car_driver_handheld',
    name: 'Driver Seat Handheld Selfie (Arm Above Wheel)',
    shortLabel: 'Driver Seat Selfie',
    description: 'Seated in the driver seat of the 2017 Range Rover Sport, right arm naturally extended holding the smartphone at eye level just above the leather steering wheel, left hand resting casually on the lower wheel rim, torso angled slightly toward the camera.',
    biomechanics: 'Right arm extended forward at a natural 65-degree bend holding the smartphone firmly, left arm resting relaxed with fingers draped over the bottom of the steering wheel. Head tilted slightly (5 degrees) toward the camera lens.',
    postureType: 'sitting',
    requiresMirror: false,
    isVehicleInteraction: true,
    spatialLocation: 'seated in the driver seat of the 2017 Range Rover Sport, Ivory perforated leather headrest behind head, steering wheel in foreground',
  },
  {
    id: 'car_steering_wheel_rest',
    name: 'Driver Seat Casual Headrest Lean',
    shortLabel: 'Driver Casual Lean',
    description: 'Seated back comfortably against the Ivory leather sports headrest, left shoulder resting against the driver door armrest, single arm holding phone at mid-chest level tilted slightly upward.',
    biomechanics: 'Single-arm front camera hold, dominant arm bent at 80 degrees holding phone at chest level, free arm resting on the center console Grand Black veneer. Relaxed neck and relaxed posture.',
    postureType: 'sitting',
    requiresMirror: false,
    isVehicleInteraction: true,
    spatialLocation: 'leaning back into the Ivory leather driver bucket seat, panoramic roof sunblind open overhead',
  },
  {
    id: 'car_passenger_chill',
    name: 'Front Passenger Seat Relaxed Angle',
    shortLabel: 'Passenger Seat',
    description: 'Seated comfortably in the front passenger seat, seatbelt worn naturally across torso, single arm holding phone toward the driver side capturing cabin depth and windshield vista.',
    biomechanics: 'Single arm extended across chest holding phone angled inward toward cabin, opposite hand resting on lap. Authentic wide-angle car interior perspective.',
    postureType: 'sitting',
    requiresMirror: false,
    isVehicleInteraction: true,
    spatialLocation: 'front passenger seat of the 2017 Range Rover Sport, Ivory perforated leather seat, Ebony dashboard and center console visible to side',
  },
  {
    id: 'standing_car_door_lean',
    name: 'Standing Beside Driver Door (Shoulder Lean)',
    shortLabel: 'Beside Driver Door',
    description: 'Standing beside the Fuji White 2017 Range Rover Sport, weight shifted onto back leg, opposite elbow resting lightly on the driver door window sill, single arm holding phone at chest level.',
    biomechanics: 'Natural standing weight shift, one elbow resting casually against the vehicle exterior door frame, dominant arm extended forward holding phone at arm length, head turned slightly toward camera.',
    postureType: 'standing',
    requiresMirror: false,
    isVehicleInteraction: true,
    spatialLocation: 'standing on the asphalt parking surface directly beside the driver door of the Fuji White 2017 Range Rover Sport',
  },
  {
    id: 'door_open_step_pose',
    name: 'Standing with Driver Door Open (Spontaneous Step)',
    shortLabel: 'Open Door Step',
    description: 'Standing with the Range Rover driver door swung open, one foot planted on the ground and one casually near the door sill, body turned slightly outward toward the front camera.',
    biomechanics: 'Dynamic standing posture, open driver door creating depth, one arm holding smartphone forward at eye level, free hand resting casually on open door interior handle.',
    postureType: 'standing',
    requiresMirror: false,
    isVehicleInteraction: true,
    spatialLocation: 'standing in the door opening of the 2017 Range Rover Sport, Ivory interior visible inside the cabin doorway and Fuji White exterior around',
  },
  {
    id: 'standing_hood_casual',
    name: 'Standing near Front Fender / Hood',
    shortLabel: 'Near Front Fender',
    description: 'Standing near the front right quarter panel of the Fuji White Range Rover, body angled at 45 degrees, one arm extended forward holding the smartphone capturing the vehicle hood and headlight.',
    biomechanics: 'Standing upright on asphalt, weight distributed naturally on both feet, single arm holding phone forward at shoulder level, free hand hanging relaxed at side.',
    postureType: 'standing',
    requiresMirror: false,
    isVehicleInteraction: true,
    spatialLocation: 'standing near the front fender of the Fuji White Range Rover Sport, distinctive pre-facelift LED headlight rings visible in background',
  },

  // --- STREET & WALKING POSES ---
  {
    id: 'mid_stride_casual_walk',
    name: 'Mid-Stride Casual Walk (Dynamic Movement)',
    shortLabel: 'Mid-Stride Walk',
    description: 'Mid-stride walking forward along the pavement, body captured mid-step with authentic gentle momentum, one arm extended forward holding the smartphone in a spontaneous on-the-go selfie.',
    biomechanics: 'One foot stepping forward with natural heel-toe contact, slight shoulder tilt aligned with stride, dominant arm extended forward at a natural 70-degree angle holding phone, free arm swinging naturally at side.',
    postureType: 'walking',
    requiresMirror: false,
    isVehicleInteraction: false,
    spatialLocation: 'walking on the paved sidewalk, background showing everyday street depth with natural subtle motion blur',
  },
  {
    id: 'standing_curb_relax',
    name: 'Relaxed Standing on Pavement Curb',
    shortLabel: 'Relaxed Standing',
    description: 'Casual standing posture on the sidewalk curb, weight settled on back hip, single arm extended forward at eye level capturing an authentic handheld snapshot.',
    biomechanics: 'Standing with relaxed spine, weight settled comfortably on one hip, dominant arm extended forward at arm length, free arm hanging naturally down.',
    postureType: 'standing',
    requiresMirror: false,
    isVehicleInteraction: false,
    spatialLocation: 'standing on the sidewalk curb, clean pavement and everyday surroundings in background',
  },
  {
    id: 'wall_lean_relaxed',
    name: 'Casual Shoulder Lean Against Wall',
    shortLabel: 'Shoulder Lean',
    description: 'Leaning one shoulder casually against a textured wall, one knee slightly bent, single arm holding smartphone at chest height angled upward.',
    biomechanics: 'One shoulder and upper back resting gently against wall surface, single arm holding phone forward, opposite arm relaxed in pocket or at side.',
    postureType: 'standing',
    requiresMirror: false,
    isVehicleInteraction: false,
    spatialLocation: 'leaning against textured wall, architectural surface and sidewalk pavers around',
  },
  {
    id: 'seated_cafe_table_pose',
    name: 'Seated at Outdoor Café Table (Elbow on Table)',
    shortLabel: 'Seated Café Table',
    description: 'Sitting at a compact outdoor café table, one elbow resting casually on the tabletop, opposite arm holding smartphone at chin level angled slightly up.',
    biomechanics: 'Upper body leaning forward slightly (10 degrees), one elbow propped on table surface, single active arm holding phone forward at natural arm length.',
    postureType: 'sitting',
    requiresMirror: false,
    isVehicleInteraction: false,
    spatialLocation: 'seated at outdoor café bistro table, cold beverage cup on tabletop, stone paved walkway in background',
  },
  {
    id: 'bench_park_relax',
    name: 'Sitting on Park Bench (Arm Extended)',
    shortLabel: 'Park Bench Relax',
    description: 'Sitting relaxed on a wooden park bench, leaning back slightly, single arm holding smartphone forward capturing palm trees and walkway behind.',
    biomechanics: 'Spine relaxed against bench slats, legs comfortably positioned, single arm extended forward at 15-degree high angle holding device.',
    postureType: 'sitting',
    requiresMirror: false,
    isVehicleInteraction: false,
    spatialLocation: 'seated on park bench, date palms and pedestrian pathway softly visible behind',
  },

  // --- BEDROOM & INDOOR POSES ---
  {
    id: 'resting_on_elbow_bed',
    name: 'Resting on One Elbow on Bed (Asymmetrical Prop)',
    shortLabel: 'Resting on Elbow',
    description: 'Resting propped up on one elbow on the mattress, torso angled at 35 degrees, single active arm extended forward holding phone at eye level, free arm supporting upper body on bed mattress.',
    biomechanics: 'Clear asymmetrical single-arm phone hold: non-dominant elbow and forearm planted firmly into the mattress supporting the elevated upper body, dominant arm extended forward holding the smartphone. Exactly one hand is holding the device.',
    postureType: 'lying',
    requiresMirror: false,
    isVehicleInteraction: false,
    spatialLocation: 'resting on one elbow on the bed mattress with soft textured duvet and pillows around',
  },
  {
    id: 'propped_bed_one_handed',
    name: 'Propped in Bed (Single-Arm Extension)',
    shortLabel: 'Propped in Bed',
    description: 'Sitting up against pillows, single arm extended forward holding smartphone at eye level, free arm resting casually across lap or under duvet.',
    biomechanics: 'Back supported by stacked pillows, dominant arm extended forward at 70cm distance holding phone with thumb and fingers around edges, free arm resting relaxed.',
    postureType: 'sitting',
    requiresMirror: false,
    isVehicleInteraction: false,
    spatialLocation: 'propped upright against bed headboard pillows, rumpled duvet covering lower legs',
  },
  {
    id: 'lying_overhead_selfie',
    name: 'Lying Flat Overhead Selfie',
    shortLabel: 'Lying Overhead',
    description: 'Lying flat on back on pillows, holding smartphone directly above face at arm length, natural wide perspective capturing ceiling and bedhead.',
    biomechanics: 'Supine posture, head resting on plush pillow, dominant arm extended upward at 85 degrees holding phone steadily overhead, free hand resting on chest.',
    postureType: 'lying',
    requiresMirror: false,
    isVehicleInteraction: false,
    spatialLocation: 'lying flat on back on plush bed pillow, rumpled duvet beneath shoulders',
  },
  {
    id: 'bed_edge_forward_lean',
    name: 'Seated on Bed Edge (Casual Forward Lean)',
    shortLabel: 'Bed Edge Sit',
    description: 'Sitting on the mattress edge, feet on the floor, one arm extended forward holding smartphone at eye level.',
    biomechanics: 'Seated upright on edge of mattress, single arm extended forward, opposite hand resting on knee. Natural torso tilt.',
    postureType: 'sitting',
    requiresMirror: false,
    isVehicleInteraction: false,
    spatialLocation: 'seated on the edge of the bed mattress, bedroom floor visible below',
  },
  {
    id: 'standing_mirror_full_length',
    name: 'Standing Mirror Selfie (Device Visible in Hand)',
    shortLabel: 'Mirror Selfie',
    description: 'Standing upright facing the full-length mirror, smartphone held at chest height in one hand angled toward mirror, capturing subject reflection and phone back in the reflection.',
    biomechanics: 'Standing balanced on two feet facing mirror surface, dominant hand gripping smartphone at upper chest level with camera lenses aimed into the mirror, opposite arm hanging relaxed at side.',
    postureType: 'standing',
    requiresMirror: true,
    isVehicleInteraction: false,
    spatialLocation: 'standing directly in front of full-length mirror, true room interior visible reflected in glass',
  },
  {
    id: 'standing_next_to_window',
    name: 'Standing beside Window (Sheer Curtain)',
    shortLabel: 'Standing by Window',
    description: 'Standing beside the window curtains, one arm extended holding phone toward face, gentle ambient light wrapping facial features.',
    biomechanics: 'Standing on floor near window frame, single arm extended holding smartphone at eye level, head turned slightly toward ambient window light.',
    postureType: 'standing',
    requiresMirror: false,
    isVehicleInteraction: false,
    spatialLocation: 'standing on the floor right beside window curtains',
  },
  {
    id: 'standing_middle_of_bedroom',
    name: 'Standing in Bedroom Center (Natural Extension)',
    shortLabel: 'Standing in Center',
    description: 'Standing upright in the open floor area of the bedroom, one arm extended forward holding smartphone at eye level.',
    biomechanics: 'Natural standing posture on floor, dominant arm extended at 75cm holding phone, free arm resting at side.',
    postureType: 'standing',
    requiresMirror: false,
    isVehicleInteraction: false,
    spatialLocation: 'standing on bedroom floor in room center, unmade bed softly out of focus behind',
  },
  {
    id: 'standing_beside_wardrobe',
    name: 'Standing beside Wardrobe Closet',
    shortLabel: 'Beside Wardrobe',
    description: 'Standing upright beside built-in closet doors, natural handheld snapshot.',
    biomechanics: 'Standing on floor beside wooden wardrobe, single arm holding smartphone at shoulder level.',
    postureType: 'standing',
    requiresMirror: false,
    isVehicleInteraction: false,
    spatialLocation: 'standing on floor beside wooden wardrobe doors',
  },
  {
    id: 'standing_near_bedroom_door',
    name: 'Standing near Interior Door',
    shortLabel: 'Near Door',
    description: 'Standing near closed interior door, casual snapshot before heading out.',
    biomechanics: 'Standing upright on floor, single arm holding phone forward at eye level.',
    postureType: 'standing',
    requiresMirror: false,
    isVehicleInteraction: false,
    spatialLocation: 'standing on bedroom floor near closed door',
  },
  {
    id: 'chair_lounging_selfie',
    name: 'Lounging in Armchair (Casual Slouch)',
    shortLabel: 'Armchair Lounge',
    description: 'Seated back in armchair, legs relaxed, single arm extended holding phone forward.',
    biomechanics: 'Seated back in deep cushioned chair, single arm extended forward at eye level, free arm resting on chair armrest.',
    postureType: 'sitting',
    requiresMirror: false,
    isVehicleInteraction: false,
    spatialLocation: 'seated in deep cushioned bedroom armchair',
  },
];

// ==========================================
// CAMERAS & PERSPECTIVES
// ==========================================
export const BEDROOM_CAMERAS: CameraOption[] = [
  {
    id: 'front_camera_eye_level',
    name: 'Smartphone Front Camera (Eye-Level 24mm)',
    perspective: 'Front-facing smartphone camera held at natural arm length (65cm) at eye level, capturing realistic 24mm wide-angle facial geometry with subtle natural perspective.',
    armReach: 'Single arm extended forward at natural 60-degree elbow bend, phone angled directly at face.',
    phoneGrip: 'Dominant hand gripping sides of smartphone securely, thumb resting near bottom edge, screen facing subject.',
    opticalNote: 'Handheld smartphone sensor look, authentic 24mm equivalent focal length, natural optical falloff with no synthetic DSLR bokeh blur.',
    isMirrorMode: false,
  },
  {
    id: 'front_camera_chest_tilt',
    name: 'Smartphone Front Camera (Chest-Level Upward Tilt)',
    perspective: 'Handheld smartphone held lower at upper chest level tilted slightly upward (10 degrees), capturing strong jawline and background architecture.',
    armReach: 'Arm held lower with elbow tucked closer to ribs (45cm distance), phone tilted subtly upward.',
    phoneGrip: 'Single hand cradling lower half of phone with fingers supporting rear back glass.',
    opticalNote: 'Realistic handheld smartphone snapshot geometry, honest arm-length wide-angle perspective.',
    isMirrorMode: false,
  },
  {
    id: 'front_camera_high_angle',
    name: 'Smartphone Front Camera (Slight High-Angle 15°)',
    perspective: 'Front camera held slightly above forehead level tilted downward 15 degrees, capturing face, collar, and foreground arm reach.',
    armReach: 'Arm extended forward and slightly elevated (70cm distance), capturing foreshortening of holding arm in lower frame corner.',
    phoneGrip: 'Single hand holding phone firmly at top corner.',
    opticalNote: 'Natural wide-angle slight high-angle smartphone selfie geometry.',
    isMirrorMode: false,
  },
  {
    id: 'car_interior_handheld',
    name: 'In-Cabin Smartphone Front Camera (24mm Wide)',
    perspective: 'Handheld smartphone front camera inside vehicle cabin, wide 24mm field of view capturing driver posture, Ivory headrest, steering wheel rim, and windshield reflections.',
    armReach: 'Right arm extended forward above center console, phone positioned at eye level 55cm from face.',
    phoneGrip: 'Single hand holding smartphone securely, opposite hand visible resting on leather steering wheel.',
    opticalNote: 'Handheld smartphone inside vehicle cabin, subtle natural lens barrel distortion, authentic automotive interior depth.',
    isMirrorMode: false,
    isVehicleInterior: true,
  },
  {
    id: 'mirror_selfie_handheld',
    name: 'Mirror Reflection Capture (Device Visible in Hand)',
    perspective: 'Rear camera aiming directly into mirror surface from 1.2 meters away, capturing reflection of subject holding the smartphone at chest level.',
    armReach: 'Phone held with one hand at upper chest level, screen facing subject and rear cameras pointing directly into mirror.',
    phoneGrip: 'Hand holding phone horizontally or vertically at chest height, fingers wrapped around edges, phone back glass and camera bump clearly visible in mirror reflection.',
    opticalNote: 'True mirror reflection geometry with camera device reflected in hand, crisp mirror surface and realistic room depth reflected.',
    isMirrorMode: true,
  },
];

// ==========================================
// LIGHTING CONDITIONS
// ==========================================
export const BEDROOM_LIGHTING: LightingOption[] = [
  {
    id: 'saudi_afternoon_warm',
    name: 'Saudi Golden Hour / Late Afternoon Warm Sun',
    timeOfDay: 'Late afternoon / Golden hour (approx. 5:15 PM)',
    lightSource: 'Low-angle warm golden sunlight (3200K) casting long soft shadows and rich amber warmth on vehicle surfaces, asphalt, and skin.',
    shadowDescription: 'Long, soft-edged warm shadows stretching across the ground; beautiful directional amber rim light along hair and shoulders.',
    atmosphere: 'Quintessential warm Saudi late-day atmosphere, clear atmospheric dust haze softening distant objects with a natural golden glow.',
    isDarkOrNight: false,
  },
  {
    id: 'saudi_midday_harsh',
    name: 'Saudi Midday Sun (Filtered under Shade Canopy)',
    timeOfDay: 'Midday (approx. 1:30 PM)',
    lightSource: 'Bright clear desert sunlight filtered through fabric parking shade or building canopy, creating diffused high-key natural illumination.',
    shadowDescription: 'Soft geometric shade patterns cast by fabric weave onto pavement and vehicle paint; gentle ambient bounce light.',
    atmosphere: 'High-visibility daytime atmosphere with genuine Saudi heat clarity and subtle warm ambient bounce from light-colored surroundings.',
    isDarkOrNight: false,
  },
  {
    id: 'saudi_night_streetlights',
    name: 'Urban Night (Sodium-Vapor & LED Streetlights)',
    timeOfDay: 'Night (approx. 10:30 PM)',
    lightSource: 'Authentic urban mixture of high-pressure sodium streetlights (warm amber 2200K) and modern cool LED parking fixtures (4000K).',
    shadowDescription: 'Multiple soft overhead shadow pools on dark asphalt, gentle ambient city glow filling deep shadows.',
    atmosphere: 'Believable Saudi nighttime street ambiance, natural smartphone low-light image processing with fine authentic high-ISO luminance noise in shadows.',
    isDarkOrNight: true,
  },
  {
    id: 'gas_station_canopy_light',
    name: 'Bright Overhead Service Station Canopy (Night)',
    timeOfDay: 'Night / Late Evening (approx. 11:00 PM)',
    lightSource: 'Powerful overhead recessed canopy LED floodlights (5000K clean white) casting bright, even illumination across the fuel island.',
    shadowDescription: 'Short sharp downward shadows directly beneath vehicle and feet, crisp highlights reflecting off polished car panels and windshield.',
    atmosphere: 'Vibrant, high-contrast highway service stop aesthetic, dark night sky surrounding the brightly illuminated white canopy oasis.',
    isDarkOrNight: true,
  },
  {
    id: 'car_interior_ambient',
    name: 'Vehicle Cabin Ambient & Instrument Glow (Night)',
    timeOfDay: 'Evening / Night (approx. 9:00 PM)',
    lightSource: 'Soft white and ice-blue backlit dashboard instruments, 10-inch InControl Touch Pro center screen glow, and soft panoramic glass roof ambient city light.',
    shadowDescription: 'Subtle intimate shadows within the cabin, gentle highlights tracing the Ivory perforated leather bolsters and Grand Black veneer.',
    atmosphere: 'Luxurious, serene nighttime driving atmosphere, passing streetlights casting occasional warm sweeping glints across the windshield.',
    isDarkOrNight: true,
  },
  {
    id: 'cafe_string_lights',
    name: 'Outdoor Café Warm Bistro String Lights (Evening)',
    timeOfDay: 'Twilight / Early Evening (approx. 8:00 PM)',
    lightSource: 'Festoon overhead bistro filament bulbs (2400K warm amber) combined with warm storefront window spill.',
    shadowDescription: 'Multiple soft intersecting warm shadows, gentle flattering illumination on face, ambient evening glow.',
    atmosphere: 'Cozy, vibrant urban café evening mood, warm hospitality ambiance.',
    isDarkOrNight: false,
  },
  {
    id: 'bright_morning_daylight',
    name: 'Soft Morning Natural Daylight (Indoor)',
    timeOfDay: 'Morning (approx. 8:30 AM)',
    lightSource: 'Clean diffused natural morning light entering through window curtains, soft wrap around subject.',
    shadowDescription: 'Gentle low-contrast shadows filling the room interior, realistic soft facial modeling.',
    atmosphere: 'Fresh, calm indoor morning stillness.',
    isDarkOrNight: false,
  },
  {
    id: 'natural_window_daylight',
    name: 'Natural Window Daylight (Diffused)',
    timeOfDay: 'Daytime (approx. 11:00 AM)',
    lightSource: 'Bright ambient daylight passing through sheer white chiffon window drapes.',
    shadowDescription: 'Feathery soft shadows, gentle directional light falloff across room.',
    atmosphere: 'Quiet, peaceful residential daytime room atmosphere.',
    isDarkOrNight: false,
  },
  {
    id: 'overhead_room_light',
    name: 'Neutral Ceiling Room Light (Indoor)',
    timeOfDay: 'Evening (approx. 8:30 PM)',
    lightSource: 'Recessed ceiling warm-white LED downlights providing balanced ambient room illumination.',
    shadowDescription: 'Natural slight downward shadows beneath chin and jawline.',
    atmosphere: 'Standard comfortable everyday indoor residential lighting.',
    isDarkOrNight: false,
  },
  {
    id: 'warm_nightstand_lamp',
    name: 'Warm Bedside Lamp (2700K Cozy)',
    timeOfDay: 'Late evening (approx. 11:30 PM)',
    lightSource: 'Single bedside nightstand lamp with fabric shade emitting intimate 2700K warm tungsten glow.',
    shadowDescription: 'Warm directional illumination on one side of face with gentle falloff into cozy room shadows.',
    atmosphere: 'Intimate, relaxing late-night private bedroom sanctuary.',
    isDarkOrNight: false,
  },
  {
    id: 'pitch_dark_screen_glow',
    name: 'Pitch Dark with Phone Screen Glow Only',
    timeOfDay: 'Deep night (approx. 2:30 AM)',
    lightSource: 'Room is in pitch darkness; the ONLY light source is the cool blue-white glow (6000K) emitted directly from the smartphone screen held in front of the face.',
    shadowDescription: 'Sharp high-contrast light falloff: facial features lit softly by the close rectangular screen, while background and surroundings fall into deep dark shadows.',
    atmosphere: 'Intimate late-night screen illumination with realistic camera sensor noise in dark shadows, completely devoid of daylight or room lights.',
    isDarkOrNight: true,
  },
];

// ==========================================
// PROPS
// ==========================================
export const BEDROOM_PROPS: PropOption[] = [
  {
    id: 'prop_none',
    name: 'No Handheld Prop (Natural Free Hand)',
    description: 'Free hand rests naturally out of frame, on lap, on steering wheel, or hanging relaxed at side without holding any extra item.',
  },
  {
    id: 'prop_car_keys',
    name: 'Range Rover Smart Key Fob',
    description: 'Sleek black and silver Land Rover smart key fob held lightly between fingers or resting on center console.',
  },
  {
    id: 'prop_paper_cup',
    name: 'Specialty Coffee Paper Takeaway Cup',
    description: 'Minimalist takeaway paper coffee cup with matte textured sleeve and subtle Arabic typography branding.',
  },
  {
    id: 'prop_cold_drink',
    name: 'Clear Iced Beverage Cup with Straw',
    description: 'Clear plastic takeaway cup filled with iced Spanish latte or cold brew coffee with subtle condensation drops.',
  },
  {
    id: 'prop_sunglasses',
    name: 'Classic Sunglasses (Held or Collar-Tucked)',
    description: 'Dark-tinted acetate sunglasses casually tucked into the shirt collar or held loosely in fingers.',
  },
  {
    id: 'prop_airpods_case',
    name: 'Wireless Earbuds Charging Case',
    description: 'Compact glossy white wireless earbud charging case held casually in free hand.',
  },
];

// ==========================================
// GLOBAL PERSONAL OPTIONS: CLOTHING
// ==========================================
export const BEDROOM_CLOTHING: ClothingOption[] = [
  {
    id: 'clothing_saudi_thobe_crisp',
    name: 'Classic White Saudi Thobe (Pristine Daily Wear)',
    category: 'saudi_traditional',
    description: 'Immaculate crisp white Saudi cotton thobe with tailored stand collar, clean chest placket, relaxed everyday fit, authentic Saudi street and lifestyle look.',
  },
  {
    id: 'clothing_saudi_thobe_shemagh',
    name: 'White Thobe with Shemagh (Casual Shoulder Drape)',
    category: 'saudi_traditional',
    description: 'Crisp white Saudi thobe paired with classic red-and-white shemagh casually draped over shoulders in a relaxed everyday non-formal style (مرزام عفوي).',
  },
  {
    id: 'clothing_minimalist_heavyweight_tee',
    name: 'Boxy Heavyweight Cotton T-Shirt & Trousers',
    category: 'casual_modern',
    description: 'Minimalist boxy-cut heavyweight cotton t-shirt in washed black or charcoal, paired with loose-tapered neutral casual trousers.',
  },
  {
    id: 'clothing_relaxed_linen_shirt',
    name: 'Relaxed Open-Collar Linen Shirt & Chinos',
    category: 'casual_modern',
    description: 'Breathable relaxed-fit open-collar linen shirt in sand beige or olive green over a soft white undershirt, paired with tailored light chinos.',
  },
  {
    id: 'clothing_oversized_hoodie',
    name: 'Oversized Neutral Streetwear Hoodie & Sweats',
    category: 'streetwear',
    description: 'Cozy oversized heavyweight fleece hoodie in heather oatmeal or asphalt gray, paired with relaxed matching sweatpants.',
  },
  {
    id: 'clothing_athletic_tee_shorts',
    name: 'Athletic Fitted Tee & Sports Shorts',
    category: 'casual_modern',
    description: 'Breathable athletic dry-fit t-shirt in dark navy and lightweight comfortable sports training shorts.',
  },
  {
    id: 'clothing_matching_summer_sleepwear',
    name: 'Comfortable Cotton Loungewear Crewneck',
    category: 'home_loungewear',
    description: 'Soft combed cotton crewneck lounge t-shirt in heather grey and breathable drawstring lounge shorts.',
  },
];

// ==========================================
// GLOBAL PERSONAL OPTIONS: HAIRSTYLES
// ==========================================
export const BEDROOM_HAIRSTYLES: HairstyleOption[] = [
  {
    id: 'hair_low_taper_fade',
    name: 'Sharp Low Taper Fade & Natural Top',
    description: 'Crisp clean low taper fade on the temples and neck with natural textured dark hair on top, styled naturally with light matte paste.',
  },
  {
    id: 'hair_wavy_textured_medium',
    name: 'Textured Wavy Dark Hair (Casual Flow)',
    description: 'Natural medium-length wavy dark hair with subtle relaxed volume, casually parted without looking over-styled.',
  },
  {
    id: 'hair_clean_buzzcut',
    name: 'Clean Disciplined Buzzcut & Trimmed Beard',
    description: 'Clean uniform short buzzcut with sharp temple hairline and neat well-groomed 3-day dark beard.',
  },
  {
    id: 'hair_casual_bedhead_stubble',
    name: 'Casual Tousled Hair & Light Stubble',
    description: 'Natural tousled dark hair with subtle relaxed texture and soft 2-day beard stubble along jawline.',
  },
];

// ==========================================
// GLOBAL PERSONAL OPTIONS: EXPRESSIONS
// ==========================================
export const BEDROOM_EXPRESSIONS: ExpressionOption[] = [
  {
    id: 'exp_relaxed_candid_smile',
    name: 'Subtle Relaxed Half-Smile (Candid & Direct)',
    description: 'Subtle genuine corner-of-the-mouth half-smile, relaxed forehead, calm confident eyes looking directly into the front smartphone camera lens.',
    microExpression: 'Subtle crinkle at outer eye corners, lips softly parted in relaxed candid warmth without forced teeth display.',
  },
  {
    id: 'exp_calm_neutral_gaze',
    name: 'Calm Understated Gaze (Natural Composure)',
    description: 'Serene, natural facial expression with neutral lips, relaxed jaw, and steady intelligent eye contact with the camera lens.',
    microExpression: 'Relaxed brow, smooth forehead, quiet contemplative demeanor reflecting everyday confidence.',
  },
  {
    id: 'exp_subtle_smirk_confident',
    name: 'Playful Corner Smirk (Effortless Everyday Mood)',
    description: 'Slight playful smirk on one side of the lips, relaxed posture, effortless candid charm.',
    microExpression: 'Asymmetrical slight lip curl, playful glint in eyes, casual spontaneous vibe.',
  },
  {
    id: 'exp_tired_late_contentment',
    name: 'Soft Late-Evening Contentment (Quiet Rest)',
    description: 'Soft relaxed eyelids, quiet content expression, breathing in the calmness of the late evening.',
    microExpression: 'Relaxed facial muscles, soft calm gaze, unhurried everyday peace.',
  },
  {
    id: 'exp_focused_candid_mirror',
    name: 'Focused Mirror Gaze (Through the Screen)',
    description: 'Composed, candid expression looking slightly through the phone screen reflection in the mirror, natural mirror selfie demeanor.',
    microExpression: 'Composed neutral lips, steady gaze directed at screen reflection.',
  },
];

// ==========================================
// GLOBAL PERSONAL OPTIONS: EYEWEAR
// ==========================================
export const BEDROOM_EYEWEAR: EyewearOption[] = [
  {
    id: 'eyewear_none',
    name: 'No Eyewear',
    description: 'Natural facial features without glasses.',
  },
  {
    id: 'eyewear_modern_acetate',
    name: 'Slim Matte Black Acetate Eyeglasses',
    description: 'Minimalist contemporary slim black rectangular acetate prescription frames with clear anti-reflective lenses.',
  },
  {
    id: 'eyewear_aviator_sunglasses',
    name: 'Dark Aviator Sunglasses',
    description: 'Classic dark-tinted metal frame aviator sunglasses with subtle warm desert reflections.',
  },
];

// ==========================================
// SAUDI AUTHENTIC EVERYDAY DETAILS
// ==========================================
export const SAUDI_BEDROOM_DETAILS: SaudiDetailOption[] = [
  {
    id: 'detail_parking_fabric_shades',
    name: 'Perforated Fabric Parking Shades & Yellow-Black Curbs',
    category: 'parking',
    description: 'Classic tensile parking shade structure made of durable perforated beige or blue fabric, curved gray steel poles, asphalt surface with yellow and black alternating painted concrete curbs, and quiet everyday parked sedans and SUVs in the background.',
  },
  {
    id: 'detail_villa_perimeter_wall',
    name: 'Textured Villa Perimeter Wall & Modern Gate',
    category: 'street',
    description: 'Warm sand-beige textured exterior profile-render (لياسة بروفايل) villa boundary wall, decorative dark sliding iron gate, outdoor split AC compressor unit mounted discreetly high on wall, clean residential sidewalk pavers.',
  },
  {
    id: 'detail_gas_station_island',
    name: 'Modern Service Station Island & Canopy',
    category: 'service',
    description: 'Modern Saudi service station fuel island, digital electronic pump readouts, clean light-gray tiled forecourt under large white illuminated canopy, convenience store glass facade, and distant highway roadside lighting.',
  },
  {
    id: 'detail_cafe_paved_walkway',
    name: 'Charcoal Walkway Pavers & Takeaway Cup',
    category: 'lifestyle',
    description: 'Anthracite interlocking walkway pavers, minimalist glass boundary screen, outdoor matte black cafe table holding a paper takeaway cup with subtle Arabic calligraphy, blurred pedestrian passersby in the background.',
  },
  {
    id: 'detail_desert_roadside',
    name: 'Desert Roadside Shoulder & Open Horizon',
    category: 'street',
    description: 'Black highway asphalt meeting golden desert sand on the road shoulder, sparse low desert shrubs, endless flat horizon under clear sky with atmospheric warm dust haze.',
  },
  {
    id: 'detail_split_ac',
    name: 'Wall Split Air Conditioner (Green 22°C LED Display)',
    category: 'indoor',
    description: 'Modern white wall-mounted split AC unit running quietly on the wall, showing a small soft green digital temperature readout of 22°C, adding quintessential modern Gulf home realism.',
  },
  {
    id: 'detail_chiffon_curtains',
    name: 'Floor-to-Ceiling Sheer Chiffon Curtains',
    category: 'indoor',
    description: 'Translucent sheer white chiffon window drapes diffusing ambient outdoor daylight into a soft luminous wrap across the room.',
  },
  {
    id: 'detail_wardrobe_closet',
    name: 'Built-in Wood-Grain Wardrobe Closet',
    category: 'indoor',
    description: 'Contemporary floor-to-ceiling built-in wardrobe with warm natural wood-grain veneer doors and brushed aluminum vertical handles.',
  },
];
