import { SceneState } from './types';

export interface BedroomPreset {
  id: string;
  title: string;
  tagline: string;
  category: 'vehicle' | 'street' | 'social' | 'indoor';
  state: Partial<SceneState>;
}

export const BEDROOM_PRESETS: BedroomPreset[] = [
  {
    id: 'preset_rr_shaded_parking',
    title: 'سيلفي الرينج روفر بالمواقف المظللة',
    tagline: 'وقفة عفوية بجانب باب السائق، رينج روفر أوتوبيوغرافي 2017 أبيض، مظلات قماشية بيج، ثوب سعودي ناصع',
    category: 'vehicle',
    state: {
      zoneId: 'shaded_parking',
      contextId: 'rr_beside_driver_door',
      poseId: 'standing_car_door_lean',
      cameraId: 'front_camera_eye_level',
      lightingId: 'saudi_afternoon_warm',
      saudiDetailId: 'detail_parking_fabric_shades',
      propId: 'prop_car_keys',
      clothingId: 'clothing_saudi_thobe_crisp',
      hairstyleId: 'hair_low_taper_fade',
      expressionId: 'exp_relaxed_candid_smile',
      eyewearId: 'eyewear_none',
    },
  },
  {
    id: 'preset_rr_driver_seat',
    title: 'داخل الرينج روفر 2017 (مقعد السائق)',
    tagline: 'داخل المقصورة الفاخرة، جلد عاجي مخرم، شاشة Touch Pro واحدة، مسكة الدركسون بيد واحدة',
    category: 'vehicle',
    state: {
      zoneId: 'shaded_parking',
      contextId: 'rr_driver_seat',
      poseId: 'car_driver_handheld',
      cameraId: 'car_interior_handheld',
      lightingId: 'saudi_afternoon_warm',
      saudiDetailId: 'detail_parking_fabric_shades',
      propId: 'prop_none',
      clothingId: 'clothing_saudi_thobe_crisp',
      hairstyleId: 'hair_low_taper_fade',
      expressionId: 'exp_relaxed_candid_smile',
      eyewearId: 'eyewear_none',
    },
  },
  {
    id: 'preset_residential_afternoon_walk',
    title: 'شارع سكني هادئ وقت العصر',
    tagline: 'مشي عفوي على رصيف حي سكني هادئ، سور فيلا بلون بيجي ومكيف سبليت خارجي، شمس ذهبية مائلة',
    category: 'street',
    state: {
      zoneId: 'residential_street',
      contextId: 'street_sidewalk_walk',
      poseId: 'mid_stride_casual_walk',
      cameraId: 'front_camera_eye_level',
      lightingId: 'saudi_afternoon_warm',
      saudiDetailId: 'detail_villa_perimeter_wall',
      propId: 'prop_airpods_case',
      clothingId: 'clothing_saudi_thobe_shemagh',
      hairstyleId: 'hair_low_taper_fade',
      expressionId: 'exp_relaxed_candid_smile',
      eyewearId: 'eyewear_none',
    },
  },
  {
    id: 'preset_gas_station_night_stop',
    title: 'استراحة محطة وقود ليلية',
    tagline: 'وقوف بجانب السيارة عند مضخة الوقود، إضاءة مظلة المحطة البيضاء، خلفية طريق سريع',
    category: 'vehicle',
    state: {
      zoneId: 'gas_station',
      contextId: 'rr_beside_driver_door',
      poseId: 'standing_car_door_lean',
      cameraId: 'front_camera_eye_level',
      lightingId: 'gas_station_canopy_light',
      saudiDetailId: 'detail_gas_station_island',
      propId: 'prop_car_keys',
      clothingId: 'clothing_minimalist_heavyweight_tee',
      hairstyleId: 'hair_low_taper_fade',
      expressionId: 'exp_subtle_smirk_confident',
      eyewearId: 'eyewear_none',
    },
  },
  {
    id: 'preset_outdoor_cafe_evening',
    title: 'مقهى رصيف خارجي مع قهوة مختصة',
    tagline: 'جلسة خارجية بمقهى حضري، كوب قهوة ورقي، إضاءة خافتة وأرضية حجرية، قميص كتان عصري',
    category: 'social',
    state: {
      zoneId: 'outdoor_cafe',
      contextId: 'seated_outdoor_table',
      poseId: 'seated_cafe_table_pose',
      cameraId: 'front_camera_chest_tilt',
      lightingId: 'cafe_string_lights',
      saudiDetailId: 'detail_cafe_paved_walkway',
      propId: 'prop_paper_cup',
      clothingId: 'clothing_relaxed_linen_shirt',
      hairstyleId: 'hair_wavy_textured_medium',
      expressionId: 'exp_relaxed_candid_smile',
      eyewearId: 'eyewear_modern_acetate',
    },
  },
  {
    id: 'preset_desert_highway_stop',
    title: 'وقفة طريق صحراوي وقت الغروب',
    tagline: 'وقفة على جانب الطريق الصحراوي والباب مفتوح، أفق رملي مفتوح، رينج روفر أبيض، هواء عليل',
    category: 'vehicle',
    state: {
      zoneId: 'desert_road_stop',
      contextId: 'rr_door_open_standing',
      poseId: 'door_open_step_pose',
      cameraId: 'front_camera_eye_level',
      lightingId: 'saudi_afternoon_warm',
      saudiDetailId: 'detail_desert_roadside',
      propId: 'prop_sunglasses',
      clothingId: 'clothing_saudi_thobe_crisp',
      hairstyleId: 'hair_low_taper_fade',
      expressionId: 'exp_calm_neutral_gaze',
      eyewearId: 'eyewear_aviator_sunglasses',
    },
  },
  {
    id: 'preset_bedroom_mirror_full',
    title: 'سيلفي المرآة / الغرفة اليومية',
    tagline: 'سيلفي المرآة الكاملة داخل الغرفة، الجوال ظاهر باليد، ملابس مريحة، واقعية منزلية هادئة',
    category: 'indoor',
    state: {
      zoneId: 'bedroom_mirror',
      contextId: 'standing_mirror_full_length_ctx',
      poseId: 'standing_mirror_full_length',
      cameraId: 'mirror_selfie_handheld',
      lightingId: 'overhead_room_light',
      saudiDetailId: 'detail_split_ac',
      propId: 'prop_none',
      clothingId: 'clothing_matching_summer_sleepwear',
      hairstyleId: 'hair_casual_bedhead_stubble',
      expressionId: 'exp_focused_candid_mirror',
      eyewearId: 'eyewear_none',
    },
  },
];
